c    writefld.fld ... プロットデータに対応するfldを作成するプログラム。
      program DEMFBfld
      implicit none
c    
      integer ndim, dim1, nspace, veclen, dec, body, I,
     &  skip, offset, stride
c
      real*8 unit, time, times, var, title(20000)

      skip = 1
      stride = 4
c    
      write(*,*)'Time?(in [seconds])'
      read(*,*)time
      write(*,*)'Time step?(in [seconds])'
      read(*,*)times
c     
c           
      open(unit = 3,err = 6060,status = 'old',file = 'colorplot')
      close(unit = 3, status = 'delete' )
6060  open(unit = 3,err = 9000,status = 'new',file = 'colorplot')   
c     
      write(3,*)'# AVS field file'
c     Following line was too long to be written
      write(3,*)'# This file was generated by', 
     &' the "FLD making supporting tool".'
      write(3,*)'# You can freely edit (Within the range of the rule). '
c
      write(3,*)' '
c
      write(3,*)'ndim = 1			',
     &'# number of dimensions in the field'
      write(3,*)'dim1 = 3000			',
     &'# dimension of axis 1'
      write(3,*)'nspace = 3			',
     &'# number of physical coordinates'
      write(3,*)'veclen = 1			',
     &'# number of components at each point'
      write(3,*)'data = float		',
     &'# data type (byte, short, integer, float, double)'
      write(3,*)'field = irregular	',
     &'# field type (uniform, rectilinear, irregular)'
      write(3,*)'label = DATA0	',
     &'# data label'
      write(3,*)' '
      write(3,*)'nstep = 79			',
     &'# number of step'
      write(3,*)' '
      write(3,*)'# Value of DATA0'
      write(3,*)' '
      write(3,*)'# Coordinate value of (X, Y, Z)'
c   ここでoffsetはcount扱い。
c   The line in colorplot starting with    
      do unit = 0.000, time, times
            offset = 0
            write(3,1002)unit, skip, offset, stride 
            do offset = 1, 3, 1
                  write(3,1003)offset, unit, skip, offset, stride
             end do
            write(3,*)'EOT'
            write(3,*)' '
c
       end do
c
c
c
c
9000  open(unit = 22,err = 9060,status = 'old',file = 'fort22')
      close(unit = 22, status = 'delete' )
9060  open(unit = 22,status = 'new',file = 'fort22')
      write(22,*) 'open error file.dat (unit=2)'
c       
c 
1001  format(1e9.3 )
1002  format('variable 1  file="',1e9.3,'pc.dat"  filetype=ascii',
     &'  skip=',1(1X,i0),'  offset=',1(1X,i0),'  stride=',1(1X,i0))
1003  format('coord   ',1(1X,i0),'  file="',1e9.3,'pc.dat"',
     & '  filetype=ascii  skip=',1(1X,i0),'  offset=',1(1X,i0),
     &'  stride=',1(1X,i0))
      end
